name: rodan
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cython
  - pip
  - pip:
    - --extra-index-url https://developer.download.nvidia.com/compute/redist
    - albumentations
    - black
    - captum
    - fairscale
    - flake8
    - h5py
    - imutils
    - monai
    - nemo_toolkit[asr]
    - onnx
    - opencv-python
    - torch>=1.12.1
    - pytorch-lightning[extra]~=1.6.4
    - lightning-bolts
    - torchvision
    - torchaudio
    - torchtext
    - torchmetrics
    - transformers[sentencepiece]>=4.21.1
    - tensorboard
    - jupyterlab
    - matplotlib
    - pandas
    - pillow
    - tokenizers
    - tqdm
    - requests
    - scikit-learn
    - scipy
