name: rodan
channels:
  - pytorch
  - nvidia
  - huggingface
  - defaults
  - conda-forge
dependencies:
  - pytorch
  - pytorch-lightning
  - torchvision
  - torchaudio
  - torchtext
  - transformers
  - torchmetrics
  - tensorboard
  - cudatoolkit
  - black
  - botocore
  - captum
  - flake8
  - h5py
  - hugginface_hub
  - hydra-core
  - jupyterlab
  - kaldi
  - librosa
  - matplotlib
  - ninja
  - onnx
  - pandas
  - pillow
  - pynini
  - pysoundfile
  - tokenizers
  - tqdm
  - requests
  - scikit-learn
  - scipy
  - sentencepiece
  - sox
  - spacy
  - unidecode
  - pip:
      - --extra-index-url https://developer.download.nvidia.com/compute/redist
      - deepspeed
      - fairscale
      - imutils
      - lightning-bolts["extra"]
      - monai
      - opencv-python
